### ISSUE TITLE
all multi extruder machines crash Cura

### ISSUE THREAD

**Issue by maukcc** [thopiekar/Cura-packaging#30] opened 2017-11-27 07:51 UTC
Every day I start my day with updating this PPA in good hopes, to see if this issue has been fixed. But sadly no. Everything else gets updated fine.
This has been going on since 2.6.99 from Juli 2017.
So for a half year now, nobody with a multi extruder machine has been able to use this PPA.
Any time frame in when this bug will be fixed?
Or is this a feature :) for some reason?

**Comment by thopiekar** [comment] 2017-12-02 11:46
Hey @maukcc ,
no it is not a "feature" 😄 The reason is that since this version I see often issues on Ubuntu.
E.g. PyQt5 is broken or something else is causing crashes.

The last days I was think about this problem here a lot and now in the end I think it is better to take a look on a port to PySide2.
The benefit I see is:
* I have already my own packages at ppa:thopiekar/pyside-git (nightly builds)
* Upgrading PyQt5 can cause issues with other applications. This way I won't touch it.

Will see how it works. Could also be that this is not easily doable as I imagine, but let's try first.

**Comment by thopiekar** [comment] 2017-12-02 15:20
Done everything to port Cura to PySide2, but still some functions are missing.

**Comment by maukcc** [comment] 2017-12-04 07:43
Great, If I can be of any help (I am not a programmer), let me know.

**Comment by maukcc** [comment] 2017-12-19 14:38
Since 3.1 we can not open Cura at all.
It will not even create the .local/share/cura folder

**Comment by thopiekar** [comment] 2017-12-19 15:53
I know, but this is nothing I can fix without an huge effort 😖

**Comment by maukcc** [comment] 2018-01-16 11:01
Update: (using the master PPA)
on Ubuntu 16.04 it installs Cura 3.0.99 and does not work
on Ubuntu 18.04 it installs Cura 3.0.3 and does work

**Comment by thopiekar** [comment] 2018-01-16 13:01
Interesting. For me it does not on Ubuntu bionic.
Could you give me more detailed info about your hardware?
Has 18.04 been installed fresh or via upgrade?
Will send you also later a command to generate a list of installed packages. I'm really curious, why running Cura still does not work for me.

**Comment by maukcc** [comment] 2018-01-16 13:15
![screenshot from 2018-01-16 14-08-51](https://user-images.githubusercontent.com/1001516/34990697-567c013a-fac7-11e7-9021-bfd7d651d369.png)
fresh install with with update&&upgrade yesterday.
16.04 is also still installed on another partition.

**Comment by thopiekar** [comment] 2018-01-16 13:21
`dpkg-query -l > ./maukcc_all_installed_packages_on_bionic`
After that try to append the file here ( eg.  zipping might be needed ) or send the via to me by mail.

Thanks @maukcc !

**Comment by maukcc** [comment] 2018-01-16 13:24
[maukcc_all_installed_packages_on_bionic.zip](https://github.com/thopiekar/Cura-packaging/files/1635247/maukcc_all_installed_packages_on_bionic.zip)

here you go

**Comment by thopiekar** [comment] 2018-01-16 13:49
What you have installed is not my package (PPA) anymore, but one provided by Ubuntu.
Yes, Cura 3.0.3 is in Ubuntus repositories!
https://packages.ubuntu.com/de/bionic/amd64/cura

According to this page, this is done by @onitake , would be nice if he could tell us about applied patches or whatever has been done compared to the upstream sources to make it work.

**Comment by onitake** [comment] 2018-01-17 08:10
Hi @thopiekar and thanks for the heads up.
Sorry for my lack of communication. It's been a busy time for me, but I agree that more collaboration would be better for everyone.

Most of the changes that we did for Debian were related to Debian policies and a few smaller things like depending on OS packages instead of using shipped dependencies (like polyclipping).
There was one important change though, and that was removing RPATH generation. That will likely cause problems on Debian. It's also important to not intermix different package versions.

AFAIK I upstreamed all code patches that were necessary (libSavitar comes to mind), and they should be in the official repos now.

What kind of crashes do you see? I'd like to take a look, perhaps I'll notice something.

**Comment by biscuitlad** [comment] 2018-01-25 16:10
OK, I can confirm I get this crash too. If I add the K4800, it continues fine. If I add the K4800 dual extruder, boom! Dies with a seg fault. This is ridiculous - it seg faults on adding a dual nozzle printer config? What?

```
Current thread 0x000073c856ce1700 (most recent call first):
  File "/usr/lib/python3/dist-packages/UM/Qt/ListModel.py", line 63 in setItems
  File "/usr/lib/python3/dist-packages/cura/Settings/ExtrudersModel.py", line 224 in __updateExtruders
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 682 in run
  File "/usr/bin/cura", line 73 in <module>
Segmentation fault (core dumped)
Running exit commands...
```
```
(xenial)xxxx@localhost:~$ lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by onitake** [comment] 2018-01-25 17:58
@biscuitlad I cannot reproduce this with Cura 3.1.0 and the shipped Vertex K8400 Dual profile (you meant 8400, right?). So either this was fixed in the meantime or there is compatibility issue somewhere. The segfault hints to a bug with Qt/PyQt. Python would simply generate the exception and exit.

2.7.0 is quite old, could you try a newer version?

**Comment by thopiekar** [comment] 2018-01-25 18:10
@onitake 2.7.0 is still in my stable PPA. I never had time to upgrade and then the crashes appeared. Therefore I kept it at 2.7.0. I will try to apply the RPATH patch. I don't know that much about rpath'ing, but however, as you think that this is the point where it most likely fails, then I should give it a try.
Just managed to find a way to apply your patch manually without changing the source format to 3.0 (quilt), so hope I can apply it soon.
If it is really the cause, then we should push this change hard into upstream. @onitake is there already a PR for it? And: Is there a good reason Ultimaker is using this functionality? Afaik, you made a change which removed rpath'ing completely. I guess, that Ultimaker will be only interested in a compromise, eg. a CMake option to turn it on/off.

Regards!

**Comment by biscuitlad** [comment] 2018-01-25 18:30
I can't, the latest PPA master crashes before it loads.



On 25 Jan 2018 5:58 pm, "Gregor Riepl" <notifications@github.com> wrote:

@biscuitlad <https://github.com/biscuitlad> I cannot reproduce this with
Cura 3.1.0 and the shipped Vertex K8400 Dual profile (you meant 8400,
right?). So either this was fixed in the meantime or there is compatibility
issue somewhere. The segfault hints to a bug with Qt/PyQt. Python would
simply generate the exception and exit.

2.7.0 is quite old, could you try a newer version?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thopiekar/Cura-packaging/issues/30#issuecomment-360547945>,
or mute the thread

**Comment by thopiekar** [comment] 2018-01-25 18:33
@biscuitlad The patch @onitake mentioned is not applied now. I just made a first test.
Also the build servers at launchpad.net (Canonical) are currently very busy. It took a day to build one package, where it normally takes max half an hour for a trivial package, like Cura (so pure Cura without any additional stuff).

**Comment by onitake** [comment] 2018-01-25 23:27
RPATH allows binding external libraries to a specific path in the filesystem.
It's most useful for bundling applications into self-contained packages. That way, you can avoid linking against incompatible OS libraries at runtime.

For a platforms with proper package and dependency management (like most Linux distributions), this is counterproductive, because it may prevent loading a library managed by the OS.

I don't think this is the source of the crash described by @biscuitlad, however.

**Comment by biscuitlad** [comment] 2018-01-26 08:35
What I meant was that I couldn't test the PPA master because that crashes before even the wizard loads. 

Yes, I did mean K8400! 

I have since added my custom gcode and messed around with the settings, everything works fine. _Except_ when I try to add another printer in the form of the K8400 dual. It's bizarre - I'm assuming there's a widget or something different added to the config interface for two nozzles that causes it to crash. The config screen for K8400 for two nozzles doesn't load - it crashes on loading it.

**Comment by onitake** [comment] 2018-01-27 15:46
Have you tried deleting (or moving away) _all_ your old settings before launching Cura?

**Comment by biscuitlad** [comment] 2018-01-27 15:58
This was on a fresh install of ubuntu LTS. The only other thing that was
installed besides xfce4 was Blender 2.79. As I say, I can play around with
the single nozzle version of K8400, save settings etc. But Add Printer ->
K8400 dual -> Add = seg fault on clicking button. That's why I'm guessing
it's a widget that tries to get loaded that kills it. Mind I don't know, as
I've never seen the dual hot end config screen!

**Comment by thopiekar** [comment] 2018-02-07 07:50
@maukcc @biscuitlad Could you please test the current master PPA?

Thanks!

**Comment by maukcc** [comment] 2018-02-07 08:39
At update and upgrade we got the following packages that were kept back:
python3-arcus
python3-savitar
after sudo apt remove cura and sudo apt autoremove and re-adding the ppa and sudo apt install cura, I get the message that package cura is not available. when I do install cura*, it just installs cura without dependencies. So that does not work either.

**Comment by thopiekar** [comment] 2018-02-07 08:40
Are you sure you made a `sudo apt update`?

**Comment by maukcc** [comment] 2018-02-07 08:41
yes, that is the 1st thing I do.

**Comment by thopiekar** [comment] 2018-02-07 08:42
Good. Just asking this because I changed some package-names. How about `apt install python3-arcus`?

**Comment by thopiekar** [comment] 2018-02-07 08:42
Oh, what I haven't tested is whether installed 3rd party plugins are blocking.

**Comment by maukcc** [comment] 2018-02-07 08:43
I did a sudo apt remove cura, and now I can not re-install cura

**Comment by thopiekar** [comment] 2018-02-07 08:45
And what if you do a manual install of python3-arcus and *-savitar?

**Comment by thopiekar** [comment] 2018-02-07 08:51
Ah, damn. Looks like I removed too much when cleaning up the master PPA :confounded:

**Comment by thopiekar** [comment] 2018-02-07 20:44
![image](https://user-images.githubusercontent.com/1847437/35940613-088efaf0-0c50-11e8-9f1b-b7c65477e2f5.png)

**Comment by maukcc** [comment] 2018-02-08 08:14
Cura installs, and crashes when any printer is selected.
I had to delete the old .local and .config files to get it to start.
[cura.log](https://github.com/thopiekar/Cura-packaging/files/1706204/cura.log)

**Comment by maukcc** [comment] 2018-02-09 10:41
the previous remark was tested with 16.04 ubuntu.
How can I tell 18.04 not to look for onitake`s ppa but to install the thopiekar ppa?

**Comment by thopiekar** [comment] 2018-02-09 10:47
@onitake Just published his own packages on Debian and thus they are on Ubuntu, too. Just enable the master PPA and it should take the packages from there since they are newer.
Additionally, I will try to build PyQt5 packages soon, so older Ubuntu versions should work, too.

**Comment by maukcc** [comment] 2018-02-09 11:17
when just updating, we got a message that some dependancies were missing. after  a remove cura, and a fresh install it starts(also with multiextruder machines), but there is no right side, as seen in the picture.
![test](https://user-images.githubusercontent.com/1001516/36025297-d64e0f6a-0d92-11e8-852b-5cbec5c688f9.png)

**Comment by thopiekar** [comment] 2018-02-09 11:19
The first time I see something like this. Seems like some packages are mixed up.
What does "apt dist-upgrade" say?

**Comment by maukcc** [comment] 2018-02-09 11:22
it says: nothing to upgrade :)

**Comment by thopiekar** [comment] 2018-02-09 11:27
Strange 😕 
Could you do this again: https://github.com/thopiekar/Cura-packaging/issues/30#issuecomment-357957223

**Comment by maukcc** [comment] 2018-02-09 11:30
here you go:
[maukcc_all_installed_packages_on_bionic.txt](https://github.com/thopiekar/Cura-packaging/files/1710771/maukcc_all_installed_packages_on_bionic.txt)

**Comment by maukcc** [comment] 2018-02-09 11:47
these are the last lines when I install onitake and then upgrade to topiekar:

> Selecting previously unselected package cura-resources-firmware.
> Preparing to unpack .../16-cura-resources-firmware_3.2.0~201802071002~rev86~pkg196~ubuntu18.04.1_all.deb ...
> Unpacking cura-resources-firmware (3.2.0~201802071002~rev86~pkg196~ubuntu18.04.1) ...
> Selecting previously unselected package python3-colorlog.
> Preparing to unpack .../17-python3-colorlog_3.1.2-1_all.deb ...
> Unpacking python3-colorlog (3.1.2-1) ...
> Errors were encountered while processing:
>  /tmp/apt-dpkg-install-Qsb1lC/03-cura-resources-materials_3.2.0~201802071001~rev210~pkg196~ubuntu18.04.1_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by maukcc** [comment] 2018-02-09 11:49
and this when I do : sudo apt --fix-broken install
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Correcting dependencies... Done
> The following packages were automatically installed and are no longer required:
>   fdm-materials libpolyclipping22 libpugixml1v5
> Use 'sudo apt autoremove' to remove them.
> The following additional packages will be installed:
>   cura-resources-materials
> The following NEW packages will be installed:
>   cura-resources-materials
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> 17 not fully installed or removed.
> Need to get 0 B/13,1 kB of archives.
> After this operation, 260 kB of additional disk space will be used.
> Do you want to continue? [Y/n]

**Comment by thopiekar** [comment] 2018-02-09 11:56
And what if you do this? Agreeing with [y]?

**Comment by maukcc** [comment] 2018-02-09 12:01
> Do you want to continue? [Y/n] y
> (Reading database ... 177464 files and directories currently installed.)
> Preparing to unpack .../cura-resources-materials_3.2.0~201802071001~rev210~pkg196~ubuntu18.04.1_all.deb ...
> Unpacking cura-resources-materials (3.2.0~201802071001~rev210~pkg196~ubuntu18.04.1) ...
> dpkg: error processing archive /var/cache/apt/archives/cura-resources-materials_3.2.0~201802071001~rev210~pkg196~ubuntu18.04.1_all.deb (--unpack):
>  trying to overwrite '/usr/share/cura/resources/materials/chromatik_pla.xml.fdm_material', which is also in package fdm-materials 3.1.0-1
> Errors were encountered while processing:
>  /var/cache/apt/archives/cura-resources-materials_3.2.0~201802071001~rev210~pkg196~ubuntu18.04.1_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
>

**Comment by thopiekar** [comment] 2018-02-09 12:04
Ah! Ok, @onitake is using different package name for the material definitions. Will try to resolve this package conflict.

**Comment by onitake** [comment] 2018-02-09 12:07
I simply used the same package name as the upstream project (fdm-materials).

**Comment by thopiekar** [comment] 2018-02-09 12:10
@onitake: But it installs files into /usr/share/cura/resources/materials. That's why in my imagination it should be called something like cura-resources-materials.
If it would install all the files in a common place like /usr/share/fdm-materials, I would agree.

**Comment by onitake** [comment] 2018-02-09 12:15
Ok, that is true. But doing that would have required changing the default path in Cura as well.
I don't think it's that big a deal, but the conflict is unfortunate.

We can resolve this either by agreeing on a common name or adding mutual Conflicts: lines to debian/control. I'm a bit reluctant to change the package name now, though...

**Comment by thopiekar** [comment] 2018-02-09 12:17
Yeah, no problem. That's why I still say inside the package that it provides fdm-materials. I can also imagine that other projects in the future can reuse the info inside these XML files.
For now I will keep my convention 😉

**Comment by onitake** [comment] 2018-02-09 12:26
Here's some more info on the possibilities: https://wiki.debian.org/PackageTransition

**Comment by thopiekar** [comment] 2018-02-10 10:37
@maukcc The package conflict should be resolved now. Could you please check whether Cura runs fine now? (With sidebar?)

**Comment by maukcc** [comment] 2018-02-10 12:14
update && upgrade works fine now. but the same result: no right side sidebar.
I also did a fresh install with the same results. here the packages before and after install:
[maukcc_all_installed_packages_on_bionic_after_cura_install.txt](https://github.com/thopiekar/Cura-packaging/files/1713351/maukcc_all_installed_packages_on_bionic_after_cura_install.txt)
[maukcc_all_installed_packages_on_bionic_before_cura_install.txt](https://github.com/thopiekar/Cura-packaging/files/1713352/maukcc_all_installed_packages_on_bionic_before_cura_install.txt)

It also will not let me load in .stl files

**Comment by thopiekar** [comment] 2018-02-10 12:17
Fresh install in meaning of reinstalling Ubuntu*?

**Comment by maukcc** [comment] 2018-02-10 12:19
No, nothing as dramatic as that :)
apt remove cura
apt autoremove

**Comment by thopiekar** [comment] 2018-02-10 12:22
Ok, did you try to remove all settings? (To remember: ~/.local/share/cura/3.2/*)
I'm really curious how it comes that the sidebar is missing. Currently Windows 10 is running here, because of some development work. Will reboot into Kubuntu asap and check myself.

**Comment by maukcc** [comment] 2018-02-10 12:24
yes, .config and .local files were removed

**Comment by thopiekar** [comment] 2018-02-10 12:30
Strange 😕 
Could you send the log of Cura then?

**Comment by maukcc** [comment] 2018-02-10 12:48
[cura.log](https://github.com/thopiekar/Cura-packaging/files/1713377/cura.log)

**Comment by thopiekar** [comment] 2018-02-10 13:19
The reason for your failed load:
```
2018-02-10 13:12:59,086 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:     self.load_file(file_name, mesh_builder, _use_numpystl = use_numpystl)
2018-02-10 13:12:59,086 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:   File "/usr/lib/uranium/plugins/FileHandlers/STLReader/STLReader.py", line 35, in load_file
2018-02-10 13:12:59,087 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:     self._loadWithNumpySTL(file_name, mesh_builder)
2018-02-10 13:12:59,087 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:   File "/usr/lib/uranium/plugins/FileHandlers/STLReader/STLReader.py", line 87, in _loadWithNumpySTL
2018-02-10 13:12:59,087 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:     for loaded_data in stl.mesh.Mesh.from_multi_file(file_name):
2018-02-10 13:12:59,087 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:   File "/usr/lib/python3/dist-packages/stl/stl.py", line 355, in from_multi_file
2018-02-10 13:12:59,088 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:     raw_data = cls.load(fh, mode=mode, speedups=speedups)
2018-02-10 13:12:59,088 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:   File "/usr/lib/python3/dist-packages/stl/stl.py", line 81, in load
2018-02-10 13:12:59,088 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:     name, data = cls._load_binary(fh, header, check_size=False)
2018-02-10 13:12:59,088 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:   File "/usr/lib/python3/dist-packages/stl/stl.py", line 108, in _load_binary
2018-02-10 13:12:59,089 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]:     count, MAX_COUNT)
2018-02-10 13:12:59,089 - ERROR - [(140205412914944)-Thread-3] UM.Logger.logException [86]: AssertionError: File too large, got 1869573152 triangles which exceeds the maximum of 10000000
```
Looks to me like NumPy-STL can't handle your file. But I don't see any errors about the sidebar. How does Cura behave when using a different printer? Eg. Ultimaker 3?

**Comment by maukcc** [comment] 2018-02-10 14:14
With UM3 (or any other) it reacts the same.

**Comment by thopiekar** [comment] 2018-02-11 14:50
@maukcc Could you please use the stable PPA now?
The packages built on top of 3.2 branches are online and I recommend the tool "ppa-purge" to remove the master PPA.

Regards!

**Comment by maukcc** [comment] 2018-02-14 13:07
1st did an update to 3.2.99(master), that did not help
then ppa-purge ppa:thopiekar/cura-master
then add ppa cura, so we got 3.2.0 stable, with same results
then ppa-purge ppa:thopiekar/cura
then it reverted to onitake`s 3.1.0 and that one works as expected with a right hand sidebar.

**Comment by thopiekar** [comment] 2018-02-14 13:11
(I hate these kind of bugs.)

Are you sure the sidebar is not collapsed? I don't know for how long this feature exists (maybe @alekseisasin remembers), but probably it is related to it (?!).

**Comment by maukcc** [comment] 2018-02-14 14:38
If we collapse the side bar, the ortho views also go to the right (and back). So that works, the sidebar is there, it just does not show anything.
What we found on the update page is : Updated sidebar to QtQuick 2.0. 
https://ultimaker.com/en/blog/52484-discover-ultimaker-cura-32
Maybe that has something to do with it?

**Comment by thopiekar** [comment] 2018-02-14 15:30
Don't think so. In my case on KDE it is just visible. 🤷

**Comment by alekseisasin** [comment] 2018-02-14 15:30
It is very strange, that after expanding it is invisible. Probably the issue in another place.

**Comment by maukcc** [comment] 2018-02-14 15:36
@alekseisasin : there never was any information in the sidebar visible. But we can see it collapse and expand.

**Comment by maukcc** [comment] 2018-02-14 16:55
fresh Ubuntu 18.04 installed, added stable cura ppa, and it still does not show any info on the sidebar.

**Comment by thopiekar** [comment] 2018-02-14 17:21
You already removed all config files, right?

**Comment by thopiekar** [comment] 2018-02-14 17:24
Oh, wait that reminds me of an error on Mac!
Let me check something in the Ultimaker forums..

**Comment by thopiekar** [comment] 2018-02-14 18:32
What happens, if you start Cura from the terminal via:
`QT_OPENGL=software cura` ?

**Comment by maukcc** [comment] 2018-02-14 22:00
That did not work, but after 

> sudo apt install QtQuick.Controls

it works :) (also for 3.2.99)

Now I just can not load any stl files
here is the log
[cura.log](https://github.com/thopiekar/Cura-packaging/files/1725794/cura.log)

**Comment by thopiekar** [comment] 2018-02-14 22:12
I missed a package.. oops 😬

Will add it asap!

**Comment by thopiekar** [comment] 2018-02-14 22:15
Are you sure that this is the package name?
I only found this:
https://packages.ubuntu.com/artful/qml-module-qtquick-controls

**Comment by onitake** [comment] 2018-02-15 07:10
Just in case, see our depedency list here: https://anonscm.debian.org/cgit/3dprinter/packages/cura.git/tree/debian/control

**Comment by onitake** [comment] 2018-02-15 07:14
Oh, and and it seems like there are too many incompatible changes in every release of Uranium, CuraEngine and Cura. We'll have to tie the versions together in the future.
A `>= x.y.z` (this version or later) dependency breaks Cura.

**Comment by thopiekar** [comment] 2018-02-15 09:55
Thanks @onitake 
But your list of deps is for 3.1.x I guess.
qml-module-qtquick-controls2 seems to be new for 3.2.x
Btw, is there something like a dependency detector for QML? Like the one provided by debhelper for shared libraries. Maintaining this list of depedencies always by hand is boring 😬

**Comment by onitake** [comment] 2018-02-16 09:02
Ok - that's interesting.
Now that you mention it... I think I saw something in the changelogs about QtQuick2.

There is, in fact, something:
`Depends: ${python3:Depends}` (plus any other non-Python deps)
But I'm not sure if it's standard practice to use.
Doesn't hurt to try it, of course.

**Comment by maukcc** [comment] 2018-02-20 13:33
If QtQuick2 is added, then this can be closed

**Closed** 2018-02-20 13:42 UTC
Labels: bug, help wanted
